<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="diffbot">

  <!-- === PROPERTIES === -->
  <!-- Wheels -->
  <xacro:property name="wheel_radius"       value="0.0325"/>            <!-- 6.5 cm / 2 -->
  <xacro:property name="wheel_separation"   value="0.29"/>              <!-- 29 cm -->
  <xacro:property name="wheel_width"        value="0.024"/>             <!-- 2.4 cm -->
  <xacro:property name="wheel_mass"         value="0.10"/>              <!-- approx. 100 g -->
  <!-- I = ½ m r² for a solid cylinder -->
  <xacro:property name="wheel_inertia"      value="${0.5 * wheel_mass * wheel_radius * wheel_radius}"/>

  <!-- Base (chassis) -->
  <xacro:property name="base_mass"          value="${15 * 0.45359237}"/> <!-- 15 lbs → kg -->
  <xacro:property name="base_length"        value="0.37"/>              <!-- 37 cm -->
  <xacro:property name="base_width"         value="0.42"/>              <!-- 42 cm -->
  <xacro:property name="base_height"        value="0.60"/>              <!-- 60 cm -->
  <!-- Rectangular prism inertia -->
  <xacro:property name="ixx" value="${base_mass * (base_width*base_width + base_height*base_height) / 12.0}"/>
  <xacro:property name="iyy" value="${base_mass * (base_length*base_length + base_height*base_height) / 12.0}"/>
  <xacro:property name="izz" value="${base_mass * (base_length*base_length + base_width*base_width)  / 12.0}"/>

  <!-- IMU -->
  <xacro:property name="imu_xyz"  value="0 0 ${wheel_radius + 0.02}"/>
  <xacro:property name="imu_rpy"  value="0 0 3.14159"/>

  <!-- LiDAR -->
  <xacro:property name="lidar_xyz" value="0 0 ${wheel_radius + 0.60}"/>
  <xacro:property name="lidar_rpy" value="0 0 0"/>

  <!-- Camera -->
  <xacro:property name="camera_xyz" value="0.15 0 ${wheel_radius + 0.55}"/>
  <xacro:property name="camera_rpy" value="0 0 0"/>

  <!-- === LINKS & JOINTS === -->
  <link name="base_link">
    <inertial>
      <mass   value="${base_mass}"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="${ixx}" ixy="0.0" ixz="0.0"
               iyy="${iyy}" iyz="0.0"
               izz="${izz}"/>
    </inertial>
  </link>

  <!-- Left wheel -->
  <link name="wheel_left_link"/>
  <joint name="wheel_left_joint" type="continuous">
    <parent link="base_link"/>
    <child  link="wheel_left_link"/>
    <origin xyz="0 ${-wheel_separation/2.0} 0" rpy="0 0 0"/>
    <axis   xyz="0 0 1"/>
  </joint>

  <!-- Right wheel -->
  <link name="wheel_right_link"/>
  <joint name="wheel_right_joint" type="continuous">
    <parent link="base_link"/>
    <child  link="wheel_right_link"/>
    <origin xyz="0 ${ wheel_separation/2.0} 0" rpy="0 0 0"/>
    <axis   xyz="0 0 1"/>
  </joint>

  <!-- IMU mount -->
  <link name="imu_link"/>
  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child  link="imu_link"/>
    <origin xyz="${imu_xyz}" rpy="${imu_rpy}"/>
  </joint>

  <!-- LiDAR mount -->
  <link name="lidar_link"/>
  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child  link="lidar_link"/>
    <origin xyz="${lidar_xyz}" rpy="${lidar_rpy}"/>
  </joint>

  <!-- Camera mount -->
  <link name="camera_link"/>
  <joint name="camera_joint" type="fixed">
    <parent link="base_link"/>
    <child  link="camera_link"/>
    <origin xyz="${camera_xyz}" rpy="${camera_rpy}"/>
  </joint>

  <!-- === ros2_control === -->
  <ros2_control name="diffbot_system" type="system">
    <hardware>
      <!-- plugin stays the same -->
      <plugin>diffbot_hardware/DiffBotSystem</plugin>

      <!-- these two lines replace your hardware_parameters block -->
      <param name="serial_port">/dev/ttyACM0</param>
      <param name="baud_rate">115200</param>
    </hardware>
    <joint name="wheel_left_joint">
      <command_interface name="velocity"/>
      <state_interface   name="velocity"/>
    </joint>
    <joint name="wheel_right_joint">
      <command_interface name="velocity"/>
      <state_interface   name="velocity"/>
    </joint>
  </ros2_control>


</robot>
