<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="diffbot">

  <!-- === MATERIALS === -->
  <material name="Green">
    <color rgba="0 0.6 0 1"/>
  </material>
  <material name="Grey">
    <color rgba="0.7 0.7 0.7 1"/>
  </material>
  <material name="White">
    <color rgba="1 1 1 1"/>
  </material>
  <material name="Red">
    <color rgba="0.8 0.1 0.1 1"/>
  </material>


  <!-- === PROPERTIES === -->
  <!-- Wheels -->
  <xacro:property name="wheel_radius"       value="0.0325"/>
  <xacro:property name="wheel_separation"   value="0.292"/>
  <xacro:property name="wheel_width"        value="0.027"/>
  <xacro:property name="wheel_mass"         value="0.034"/>
  <xacro:property name="wheel_inertia"      value="${0.5 * wheel_mass * wheel_radius * wheel_radius}"/>

  <!-- Base (cylinder chassis) -->
  <xacro:property name="base_mass"          value="${15 * 0.45359237}"/>
  <xacro:property name="base_radius"        value="0.21"/>
  <xacro:property name="base_height"        value="0.55"/>
  <xacro:property name="ixx" value="${base_mass * (3 * base_radius * base_radius + base_height * base_height) / 12.0}"/>
  <xacro:property name="iyy" value="${base_mass * (3 * base_radius * base_radius + base_height * base_height) / 12.0}"/>
  <xacro:property name="izz" value="${0.5 * base_mass * base_radius * base_radius}"/>

  <!-- Sensors -->
  <xacro:property name="imu_xyz"    value="0 0 ${wheel_radius + 0.01}"/>
  <xacro:property name="imu_rpy"    value="0 0 3.14159"/>
  <xacro:property name="lidar_xyz"  value="0 0 ${wheel_radius + 0.55}"/>
  <xacro:property name="lidar_rpy"  value="0 0 0"/>
  <xacro:property name="camera_xyz" value="0.15 0 ${wheel_radius + 0.5}"/>
  <xacro:property name="camera_rpy" value="0 0 0"/>

  <!-- === LINKS === -->
  <link name="base_link">
    <inertial>
      <mass value="${base_mass}"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="${ixx}" ixy="0.0" ixz="0.0"
               iyy="${iyy}" iyz="0.0"
               izz="${izz}"/>
    </inertial>
    <visual>
      <geometry>
        <cylinder radius="${base_radius}" length="${base_height}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="Green"/>
    </visual>
  </link>

  <link name="wheel_left_link">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="1.5707 0 0"/>
      <material name="Grey"/>
    </visual>
  </link>

  <link name="wheel_right_link">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="1.5707 0 0"/>
      <material name="Grey"/>
    </visual>
  </link>

  <link name="imu_link">
    <visual>
      <geometry>
        <box size="0.05 0.05 0.02"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="White"/>
    </visual>
  </link>

  <link name="lidar_link">
    <visual>
      <geometry>
        <cylinder radius="0.05" length="0.03"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="White"/>
    </visual>
  </link>

  <link name="camera_link">
    <visual>
      <geometry>
        <box size="0.05 0.05 0.05"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="White"/>
    </visual>
  </link>

  <!-- === Ultrasonic Sensor Links === -->
<link name="ultrasonic_a_link">
  <visual>
    <geometry>
      <cylinder radius="0.01" length="0.02"/>
    </geometry>
    <origin xyz="0 0 0" rpy="0 1.5708 0"/> <!-- sideways orientation -->
    <material name="Red"/>
  </visual>
</link>

<link name="ultrasonic_b_link">
  <visual>
    <geometry>
      <cylinder radius="0.01" length="0.02"/>
    </geometry>
    <origin xyz="0 0 0" rpy="0 1.5708 0"/>
    <material name="Red"/>
  </visual>
</link>

<link name="ultrasonic_c_link">
  <visual>
    <geometry>
      <cylinder radius="0.01" length="0.02"/>
    </geometry>
    <origin xyz="0 0 0" rpy="0 1.5708 0"/>
    <material name="Red"/>
  </visual>
</link>


  <!-- === JOINTS === -->
  <joint name="wheel_left_joint" type="continuous">
    <parent link="base_link"/>
    <child  link="wheel_left_link"/>
    <origin xyz="0 ${-wheel_separation/2.0} 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <joint name="wheel_right_joint" type="continuous">
    <parent link="base_link"/>
    <child  link="wheel_right_link"/>
    <origin xyz="0 ${wheel_separation/2.0} 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child  link="imu_link"/>
    <origin xyz="${imu_xyz}" rpy="${imu_rpy}"/>
  </joint>

  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child  link="lidar_link"/>
    <origin xyz="${lidar_xyz}" rpy="${lidar_rpy}"/>
  </joint>

  <joint name="camera_joint" type="fixed">
    <parent link="base_link"/>
    <child  link="camera_link"/>
    <origin xyz="${camera_xyz}" rpy="${camera_rpy}"/>
  </joint>

  <!-- === Ultrasonic Sensor Joints === -->
  <joint name="ultrasonic_a_joint" type="fixed">
    <parent link="base_link"/>
    <child link="ultrasonic_a_link"/>
    <origin xyz="${base_radius} 0 ${-base_height/2 + 0.02}" rpy="0 0 0"/>
  </joint>

  <joint name="ultrasonic_b_joint" type="fixed">
    <parent link="base_link"/>
    <child link="ultrasonic_b_link"/>
    <origin xyz="${base_radius * cos(-0.5236)} ${base_radius * sin(-0.5236)} ${-base_height/2 + 0.02}" rpy="0 0 -0.5236"/>
  </joint>

  <joint name="ultrasonic_c_joint" type="fixed">
    <parent link="base_link"/>
    <child link="ultrasonic_c_link"/>
    <origin xyz="${base_radius * cos(0.5236)} ${base_radius * sin(0.5236)} ${-base_height/2 + 0.02}" rpy="0 0 0.5236"/>
  </joint>


  <!-- === ros2_control === -->
  <ros2_control name="diffbot_system" type="system">
    <hardware>
      <plugin>diffbot_hardware/DiffBotSystem</plugin>
      <param name="serial_port">/dev/ttyUSB_TEENSY</param>
      <param name="baud_rate">115200</param>
    </hardware>
    <joint name="wheel_left_joint">
      <command_interface name="velocity"/>
      <state_interface   name="velocity"/>
      <state_interface   name="position"/>
    </joint>
    <joint name="wheel_right_joint">
      <command_interface name="velocity"/>
      <state_interface   name="velocity"/>
      <state_interface   name="position"/>
    </joint>
  </ros2_control>

</robot>