teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1               # Left stick vertical (forward/back)
    scale_linear:
      x: 0.5
    scale_linear_turbo:
      x: 1.0
    
    axis_angular:
      yaw: 0                # Left stick horizontal (turn)
    scale_angular:
      yaw: 0.5  
    scale_angular_turbo:
      yaw: 1.0 

    require_enable_button: true
    enable_button: 5             # R1 must be held to move
    enable_turbo_button: 4       #L1 for turbo
   # publish_stamped_twist: true