slam_toolbox:
  ros__parameters:
    #–– Basic frames and topics ––
    mode: mapping
    map_frame: map
    odom_frame: odom
    base_frame: base_link
    scan_topic: /scan

    #–– Publish the global map on /map every 0.5 s ––
    publish_map_odom_transform: true
    transform_publish_period: 0.02
    publish_period_sec: 0.5

    #–– Keep FIFO queues big enough to avoid drops ––
    scan_queue_size: 20
    transform_queue_size: 20
    transform_tolerance: 0.1

    #–– Lifecycle / map‐saving support (optional) ––
    use_lifecycle_manager: true
    use_map_saver: true

    map_start_pose: [0.0, 0.0, 0.0]   # [x, y, yaw] in the map frame :contentReference[oaicite:0]{index=0}

    # optional: give it a little longer to find your TFs
    transform_timeout: 0.2
    tf_buffer_duration: 10.0
