# src/robot_bringup/config/robot_controllers.yaml

controller_manager:
  ros__parameters:
    # controller_manager settings
    update_rate: 100
    autostart: true

    # controller types
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    forward_command_controller:
      type: diff_drive_controller/DiffDriveController

joint_state_broadcaster:
  ros__parameters: {}

forward_command_controller:
  ros__parameters:
    left_wheel_names:   ["wheel_left_joint"]
    right_wheel_names:  ["wheel_right_joint"]
    wheel_separation:   0.25
    wheel_radius:       0.0325
    cmd_vel_timeout:    2.0
    use_stamped_vel:    true
    enable_odom_tf:     true
    odom_frame_id:      "odom"
    base_frame_id:      "base_link"
    open_loop:          false
