controller_manager:
  ros__parameters:
    # controller_manager settings
    update_rate: 100
    autostart: true

    # controller types
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    forward_command_controller:
      type: diff_drive_controller/DiffDriveController

joint_state_broadcaster:
  ros__parameters: {}

forward_command_controller:
  ros__parameters:
    left_wheel_names:   ["wheel_left_joint"]
    right_wheel_names:  ["wheel_right_joint"]
    wheel_separation:   0.294
    wheel_radius:       0.03329
    cmd_vel_timeout:    0.3
    use_stamped_vel:    true
    publish_rate:       50.0
    # (the rest of your diff_drive defaults will be pulled from the
    #  diff_drive_controller_parameter.yaml, so you only need to override
    #  the things you really care about here)
